//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelOtomasyonu.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cyper8Entities : DbContext
    {
        public cyper8Entities()
            : base("name=cyper8Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_KULLANICI_GIRIS> TBL_KULLANICI_GIRIS { get; set; }
        public virtual DbSet<TBL_SIRKET_SECIMI> TBL_SIRKET_SECIMI { get; set; }
    }
}
