//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelOtomasyonu.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SIRKET_SECIMI
    {
        public int ID { get; set; }
        public string KODU { get; set; }
        public string KISADI { get; set; }
        public string TICARIUNVAN { get; set; }
        public string YETKILISI { get; set; }
    }
}
